# Generated by Django 4.2.3 on 2023-08-01 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_number", models.CharField(default=87168949, max_length=8)),
                ("pick_up_location", models.CharField(max_length=200)),
                ("drop_off_location", models.CharField(max_length=200)),
                ("booked_from", models.DateTimeField()),
                ("booked_until", models.DateTimeField()),
                (
                    "booking_type",
                    models.CharField(
                        choices=[("days", "By Days"), ("distance", "By Distance")],
                        max_length=10,
                    ),
                ),
                (
                    "booking_amount",
                    models.DecimalField(decimal_places=5, max_digits=10),
                ),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "booking_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("canceled", "Canceled"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "car_type",
                    models.CharField(
                        choices=[
                            ("sedan", "Sedan"),
                            ("SUV", "SUV"),
                            ("minivan", "MiniVan"),
                            ("sport", "Sport"),
                        ],
                        max_length=10,
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="cars/")),
                ("model", models.CharField(max_length=100)),
                (
                    "price_per_hour",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("price_per_km", models.DecimalField(decimal_places=2, max_digits=10)),
                ("number_of_seats", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
                    ),
                ),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.car"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_id", models.CharField(max_length=255)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.booking"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="booking",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.car"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
