# Generated by Django 4.2.3 on 2023-07-31 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="image",
            field=models.ImageField(blank=True, upload_to="cars"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="booking_number",
            field=models.CharField(default=77036543, max_length=8),
        ),
    ]
