# Generated by Django 4.0.2 on 2023-08-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_booking_booking_number_alter_car_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(default=39855990, max_length=8),
        ),
    ]
