# Generated by Django 4.0.2 on 2023-08-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_booking_booking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(default=15432741, max_length=8),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('active', 'Active'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='idle', max_length=10),
        ),
    ]
