# Generated by Django 4.2.3 on 2023-08-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_booking_booking_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="booking_number",
            field=models.CharField(default=56971573, max_length=8),
        ),
        migrations.AlterField(
            model_name="booking",
            name="booking_status",
            field=models.CharField(
                choices=[
                    ("idle", "Idle"),
                    ("upcomming", "Upcomming"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("canceled", "Canceled"),
                ],
                default="idle",
                max_length=10,
            ),
        ),
    ]
