# Generated by Django 4.2.4 on 2023-08-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_booking_booking_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="booking_number",
            field=models.CharField(default=51415581, max_length=8),
        ),
        migrations.AlterField(
            model_name="car",
            name="image",
            field=models.ImageField(blank=True, max_length=255, upload_to="cars/"),
        ),
    ]
