# Generated by Django 4.2.4 on 2023-08-27 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_alter_booking_booking_number_alter_car_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="booking_number",
            field=models.CharField(default=57132340, max_length=8),
        ),
        migrations.AlterField(
            model_name="payment",
            name="booking",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="core.booking"
            ),
        ),
    ]
