# Generated by Django 4.2.4 on 2024-08-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_payment_status_alter_booking_booking_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="booking_number",
            field=models.CharField(default=89481728, max_length=8),
        ),
    ]
