# Generated by Django 4.2.4 on 2024-08-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_alter_booking_booking_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="booking_number",
            field=models.CharField(default=63857092, max_length=8),
        ),
    ]
