# Generated by Django 4.2.4 on 2024-08-08 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Highlights",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "availability",
                    models.CharField(
                        choices=[("all_year", "All Year"), ("half_year", "Half Year")],
                        max_length=55,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("all_year", "All Year"), ("half_year", "Half Year")],
                        max_length=55,
                    ),
                ),
                ("sub_category", models.CharField(max_length=255)),
                ("cover_image", models.ImageField(upload_to="tour_covers")),
                ("duration", models.DecimalField(decimal_places=2, max_digits=10)),
                ("distance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price_from", models.DecimalField(decimal_places=2, max_digits=10)),
                ("pickup", models.BooleanField()),
                ("featured", models.BooleanField()),
                ("pickup_information", models.TextField()),
                ("additional_notes", models.TextField()),
                ("highlights", models.ManyToManyField(to="tour.highlights")),
            ],
        ),
        migrations.CreateModel(
            name="TourImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="tour_images")),
                (
                    "tour_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_ids",
                        to="tour.tour",
                    ),
                ),
            ],
        ),
    ]
