# Generated by Django 4.2.4 on 2024-08-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tour", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tour",
            name="category",
            field=models.CharField(
                choices=[
                    ("airport_transfer", "Airport Transfer"),
                    ("private_transfer", "Private Transfer"),
                    ("normal_trip", "Normal Trip"),
                ],
                max_length=55,
            ),
        ),
    ]
