# Generated by Django 4.2.4 on 2024-08-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlights',
            name='title',
            field=models.CharField(max_length=55, unique=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
