# Generated by Django 4.2.4 on 2024-08-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_alter_highlights_title_alter_hotel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='distance',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tour',
            name='duration',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
